### ISSUE TITLE
When will the 1.1.2 version go up in the Maven Repository?

### ISSUE THREAD

**Issue by underbell** [mariadb-corporation/mariadb-connector-r2dbc#33]
How can I use the version 1.1.2? 
This version does not exist in Maven central.
Do you have any other repository?

**Comment by FloEberle** [comment]
I am waiting for this too, since when upgrading to spring boot 2.7.x it seems to behave weirdly with the driver in the latest available version 1.1.1-rc.

https://spring.io/blog/2022/05/19/spring-boot-2-7-0-available-now
https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-2021.2-%28Raj%29-Release-Notes#compatibility-with-r2dbc-09
> Spring Data R2DBC can be used with R2DBC 0.9. **To use R2DBC 0.9 you require an R2DBC 0.9-compatible driver and you need to upgrade the specification interface to 0.9.0.RELEASE.** When using Maven, your pom.xml could contain the following dependencies:

**Comment by linghengqian** [comment]
But 1.1.2 is already in Maven Central, see https://mvnrepository.com/artifact/org.mariadb/r2dbc-mariadb/1.1.2 .
